### ISSUE TITLE
mix test fails with compilation error

### ISSUE THREAD

**Issue by sobolevn** [joaomdmoura/machinery#46]
I have a `phonix1.4` project. It works fine when calling `mix compile`. But fails for `mix test`.

```
$ mix test

==> machinery
Compiling 11 files (.ex)

== Compilation error in file lib/machinery/endpoint.ex ==
** (ArgumentError) invalid :json_decoder option. The module Poison is not loaded and could not be found
    (plug) lib/plug/parsers/json.ex:54: Plug.Parsers.JSON.validate_decoder!/1
    (plug) lib/plug/parsers/json.ex:32: Plug.Parsers.JSON.init/1
    (plug) lib/plug/parsers.ex:245: anonymous fn/3 in Plug.Parsers.convert_parsers/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/parsers.ex:228: Plug.Parsers.convert_parsers/2
    (plug) lib/plug/parsers.ex:224: Plug.Parsers.init/1
    (plug) lib/plug/builder.ex:302: Plug.Builder.init_module_plug/4
    (plug) lib/plug/builder.ex:286: anonymous fn/5 in Plug.Builder.compile/3
could not compile dependency :machinery, "mix compile" failed. You can recompile thisdependency with "mix deps.compile machinery", update it with "mix deps.update machinery" or clean it with "mix deps.clean machinery"
```

I am using: `{:machinery, "~> 0.17.0"},`

**Comment by joaomdmoura** [comment]
This is fixed now on master 😄
